#include "nanoquant/workflow.hpp"

#include <algorithm>
#include <array>
#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <sys/wait.h>

namespace nanoquant {
namespace {

std::string shell_quote(const std::filesystem::path& path) {
    std::string raw = path.string();
    std::string quoted = "'";
    for (const char ch : raw) {
        if (ch == '\'') {
            quoted += "'\\''";
        } else {
            quoted += ch;
        }
    }
    quoted += "'";
    return quoted;
}

std::string shell_quote(const std::string& value) {
    return shell_quote(std::filesystem::path(value));
}

std::string slugify(std::string value) {
    std::replace(value.begin(), value.end(), '/', '-');
    std::replace(value.begin(), value.end(), ':', '-');
    for (char& ch : value) {
        if (!std::isalnum(static_cast<unsigned char>(ch)) && ch != '-' && ch != '_') {
            ch = '-';
        }
        ch = static_cast<char>(std::tolower(static_cast<unsigned char>(ch)));
    }
    return value;
}

std::filesystem::path default_llama_cpp_dir(const WorkflowOptions& options) {
    if (!options.llama_cpp_dir.empty()) {
        return options.llama_cpp_dir;
    }
    if (const char* env = std::getenv("LLAMA_CPP_DIR")) {
        return env;
    }
    return "third_party/llama.cpp";
}

std::filesystem::path quantize_binary(const std::filesystem::path& llama_cpp_dir) {
    const std::array<std::filesystem::path, 5> candidates = {
        llama_cpp_dir / "build/bin/llama-quantize",
        llama_cpp_dir / "build/bin/quantize",
        llama_cpp_dir / "llama-quantize",
        llama_cpp_dir / "quantize",
        "llama-quantize",
    };
    for (const auto& candidate : candidates) {
        if (candidate == "llama-quantize" || std::filesystem::exists(candidate)) {
            return candidate;
        }
    }
    return candidates.front();
}

std::string normalize_token(std::string token) {
    token.erase(std::remove_if(token.begin(), token.end(),
                               [](unsigned char ch) { return !std::isalnum(ch); }),
                token.end());
    std::transform(token.begin(), token.end(), token.begin(),
                   [](unsigned char ch) { return static_cast<char>(std::tolower(ch)); });
    return token;
}

std::set<std::string> token_set(const std::string& text) {
    std::istringstream stream(text);
    std::set<std::string> tokens;
    std::string token;
    while (stream >> token) {
        token = normalize_token(token);
        if (token.size() > 2U) {
            tokens.insert(token);
        }
    }
    return tokens;
}

void write_file(const std::filesystem::path& path, const std::string& content) {
    std::filesystem::create_directories(path.parent_path());
    std::ofstream file(path);
    if (!file) {
        throw std::runtime_error("failed to write " + path.string());
    }
    file << content;
}

std::string modelfile_content(const WorkflowOptions& options, const std::filesystem::path& gguf_path) {
    std::ostringstream out;
    out << "FROM " << gguf_path.string() << "\n";
    out << "PARAMETER temperature 0.7\n";
    out << "PARAMETER top_p 0.9\n";
    out << "PARAMETER num_ctx 4096\n";
    out << "SYSTEM You are a locally running compressed model. Be accurate, concise, and transparent about uncertainty.\n";
    out << "# Generated by NanoQuant for " << options.model_id << "\n";
    return out.str();
}

std::string report_markdown(const WorkflowOptions& options,
                            const WorkflowPlan& plan,
                            const std::optional<ComparisonReport>& comparison) {
    std::ostringstream out;
    out << "# NanoQuant Run Report\n\n";
    out << "- model: `" << options.model_id << "`\n";
    out << "- quantization: `" << options.quantization << "`\n";
    out << "- ollama model: `" << options.ollama_name << "`\n";
    if (!options.base_ollama_name.empty()) {
        out << "- reference model: `" << options.base_ollama_name << "`\n";
    } else if (!options.reference_ollama_name.empty()) {
        out << "- reference model: `" << options.reference_ollama_name << "`\n";
    }
    out << "- pull command: `ollama pull " << options.ollama_name << "`\n";
    out << "- artifact: `" << plan.quantized_gguf.string() << "`\n\n";

    if (comparison.has_value()) {
        out << "## Comparison\n\n";
        out << "- lexical overlap: `" << comparison->lexical_overlap << "`\n";
        out << "- length ratio: `" << comparison->length_ratio << "`\n";
        out << "- likely degraded: `" << (comparison->likely_degraded ? "yes" : "no") << "`\n\n";
        out << "### Base Output\n\n```text\n" << comparison->base_output << "\n```\n\n";
        out << "### Compressed Output\n\n```text\n" << comparison->compressed_output << "\n```\n\n";
        if (comparison->likely_degraded) {
            out << build_tuning_recommendation(options, *comparison);
        }
    } else {
        out << "Comparison skipped. Pass `--base-ollama-name <name>` to compare against an existing Ollama model.\n";
    }

    return out.str();
}

}  // namespace

bool command_exists(const std::string& command) {
    const std::string check = "command -v " + command + " >/dev/null 2>&1";
    return std::system(check.c_str()) == 0;
}

CommandResult run_command_capture(const std::string& command) {
    CommandResult result;
    const std::string wrapped = command + " 2>&1";
    FILE* pipe = popen(wrapped.c_str(), "r");
    if (pipe == nullptr) {
        result.output = "failed to start command";
        return result;
    }

    std::array<char, 4096> buffer{};
    while (fgets(buffer.data(), static_cast<int>(buffer.size()), pipe) != nullptr) {
        result.output += buffer.data();
    }

    const int status = pclose(pipe);
    if (WIFEXITED(status)) {
        result.exit_code = WEXITSTATUS(status);
    } else {
        result.exit_code = status;
    }
    return result;
}

WorkflowPlan build_workflow_plan(const WorkflowOptions& options) {
    if (options.model_id.empty()) {
        throw std::invalid_argument("--model-id is required");
    }
    if (options.ollama_name.empty()) {
        throw std::invalid_argument("--ollama-name is required");
    }

    const std::filesystem::path llama_cpp = default_llama_cpp_dir(options);
    WorkflowPlan plan;
    const std::string slug = slugify(options.model_id);
    plan.model_dir = options.output_dir / "hf" / slug;
    plan.fp16_gguf = options.output_dir / "gguf" / (slug + "-f16.gguf");
    plan.quantized_gguf = options.output_dir / "gguf" / (slug + "-" + options.quantization + ".gguf");
    plan.modelfile = options.output_dir / "ollama" / (options.ollama_name + ".Modelfile");
    if (!options.reference_ollama_name.empty()) {
        plan.reference_modelfile = options.output_dir / "ollama" / (options.reference_ollama_name + ".Modelfile");
    }
    plan.report_file = options.output_dir / "reports" / (options.ollama_name + ".md");

    if (command_exists("huggingface-cli")) {
        plan.steps.push_back({"Download Hugging Face snapshot",
                              "huggingface-cli download " + shell_quote(options.model_id) +
                                  " --local-dir " + shell_quote(plan.model_dir),
                              true});
    } else {
        plan.steps.push_back({"Download Hugging Face snapshot",
                              "git clone https://huggingface.co/" + options.model_id + " " + shell_quote(plan.model_dir),
                              true});
    }

    plan.steps.push_back({"Convert HF checkpoint to GGUF",
                          "python3 " + shell_quote(llama_cpp / "convert_hf_to_gguf.py") + " " +
                              shell_quote(plan.model_dir) + " --outfile " + shell_quote(plan.fp16_gguf) +
                              " --outtype f16",
                          true});

    if (!options.reference_ollama_name.empty()) {
        plan.steps.push_back({"Create reference Ollama model",
                              "ollama create " + shell_quote(options.reference_ollama_name) + " -f " +
                                  shell_quote(plan.reference_modelfile),
                              true});
    }

    plan.steps.push_back({"Quantize GGUF",
                          shell_quote(quantize_binary(llama_cpp)) + " " + shell_quote(plan.fp16_gguf) + " " +
                              shell_quote(plan.quantized_gguf) + " " + options.quantization,
                          true});

    plan.steps.push_back({"Create Ollama model",
                          "ollama create " + shell_quote(options.ollama_name) + " -f " + shell_quote(plan.modelfile),
                          true});

    if (options.ollama_push) {
        plan.steps.push_back({"Push Ollama model",
                              "ollama push " + shell_quote(options.ollama_name),
                              true});
    }

    plan.steps.push_back({"Smoke-test compressed Ollama model",
                          "ollama run " + shell_quote(options.ollama_name) + " " + shell_quote(options.prompt),
                          false});

    const std::string comparison_model =
        !options.base_ollama_name.empty() ? options.base_ollama_name : options.reference_ollama_name;
    if (!comparison_model.empty()) {
        plan.steps.push_back({"Compare reference and compressed outputs",
                              "ollama run " + shell_quote(comparison_model) + " " + shell_quote(options.prompt) +
                                  " && ollama run " + shell_quote(options.ollama_name) + " " + shell_quote(options.prompt),
                              false});
    }

    return plan;
}

void print_workflow_plan(const WorkflowPlan& plan) {
    std::cout << "NanoQuant HF -> GGUF -> Ollama plan\n";
    std::cout << "model_dir:      " << plan.model_dir << '\n';
    std::cout << "fp16_gguf:      " << plan.fp16_gguf << '\n';
    std::cout << "quantized_gguf: " << plan.quantized_gguf << '\n';
    std::cout << "modelfile:      " << plan.modelfile << '\n';
    if (!plan.reference_modelfile.empty()) {
        std::cout << "referencefile:  " << plan.reference_modelfile << '\n';
    }
    std::cout << "report:         " << plan.report_file << "\n\n";

    for (std::size_t index = 0; index < plan.steps.size(); ++index) {
        std::cout << index + 1U << ". " << plan.steps[index].title << '\n';
        std::cout << "   " << plan.steps[index].command << '\n';
    }
}

ComparisonReport compare_outputs(const std::string& base_output, const std::string& compressed_output) {
    ComparisonReport report;
    report.base_output = base_output;
    report.compressed_output = compressed_output;

    const auto base_tokens = token_set(base_output);
    const auto compressed_tokens = token_set(compressed_output);
    std::size_t intersection = 0;
    for (const auto& token : base_tokens) {
        if (compressed_tokens.contains(token)) {
            ++intersection;
        }
    }

    const std::size_t denominator = std::max<std::size_t>(base_tokens.size(), 1U);
    report.lexical_overlap = static_cast<double>(intersection) / static_cast<double>(denominator);
    report.length_ratio = base_output.empty() ? 0.0 : static_cast<double>(compressed_output.size()) /
                                                       static_cast<double>(base_output.size());
    report.likely_degraded = report.lexical_overlap < 0.20 || report.length_ratio < 0.35 || report.length_ratio > 2.80;
    return report;
}

std::string build_tuning_recommendation(const WorkflowOptions& options, const ComparisonReport& report) {
    std::ostringstream out;
    out << "## Distillation / Fine-Tuning Recommendation\n\n";
    out << "The compressed model looks degraded by the cheap lexical guardrail. Do not tune blindly.\n\n";
    out << "Recommended path:\n\n";
    out << "1. Build a task-specific prompt set for the use case.\n";
    out << "2. Run the original model as teacher and store `{prompt, teacher_answer}` pairs.\n";
    out << "3. Fine-tune a LoRA adapter against the teacher answers, then merge/export to GGUF.\n";
    out << "4. Re-quantize and rerun this comparison before publishing.\n\n";
    out << "Observed guardrail values:\n\n";
    out << "- lexical overlap: `" << report.lexical_overlap << "`\n";
    out << "- length ratio: `" << report.length_ratio << "`\n\n";
    out << "Suggested dataset command sketch:\n\n";
    out << "```bash\n";
    const std::string teacher_model =
        !options.base_ollama_name.empty() ? options.base_ollama_name : options.reference_ollama_name;
    out << "ollama run " << teacher_model << " < prompts.txt > teacher_answers.txt\n";
    out << "# Convert prompts + teacher_answers into JSONL for your LoRA trainer.\n";
    out << "```\n\n";
    return out.str();
}

int run_workflow(const WorkflowOptions& options) {
    WorkflowPlan plan = build_workflow_plan(options);
    std::filesystem::create_directories(options.output_dir);
    std::filesystem::create_directories(plan.modelfile.parent_path());
    std::filesystem::create_directories(plan.report_file.parent_path());
    std::filesystem::create_directories(plan.fp16_gguf.parent_path());

    write_file(plan.modelfile, modelfile_content(options, plan.quantized_gguf));
    if (!plan.reference_modelfile.empty()) {
        write_file(plan.reference_modelfile, modelfile_content(options, plan.fp16_gguf));
    }

    if (!options.execute) {
        print_workflow_plan(plan);
        std::cout << "\nDry run only. Add --execute to run the external tools.\n";
        return 0;
    }

    for (const auto& step : plan.steps) {
        if (step.title == "Smoke-test compressed Ollama model" ||
            step.title == "Compare reference and compressed outputs") {
            continue;
        }
        std::cout << "\n==> " << step.title << '\n';
        const CommandResult result = run_command_capture(step.command);
        std::cout << result.output;
        if (result.exit_code != 0 && step.required) {
            std::cerr << "step failed with exit code " << result.exit_code << '\n';
            return result.exit_code;
        }
    }

    std::optional<ComparisonReport> comparison;
    const std::string comparison_model =
        !options.base_ollama_name.empty() ? options.base_ollama_name : options.reference_ollama_name;
    if (!comparison_model.empty()) {
        const std::string base_command = "ollama run " + shell_quote(comparison_model) + " " + shell_quote(options.prompt);
        const std::string compressed_command = "ollama run " + shell_quote(options.ollama_name) + " " + shell_quote(options.prompt);
        const CommandResult base = run_command_capture(base_command);
        const CommandResult compressed = run_command_capture(compressed_command);
        comparison = compare_outputs(base.output, compressed.output);
        std::cout << "\ncomparison lexical_overlap=" << comparison->lexical_overlap
                  << " length_ratio=" << comparison->length_ratio
                  << " degraded=" << (comparison->likely_degraded ? "yes" : "no") << '\n';
    }

    write_file(plan.report_file, report_markdown(options, plan, comparison));
    std::cout << "wrote report: " << plan.report_file << '\n';
    return 0;
}

}  // namespace nanoquant
